<a href="https://colab.research.google.com/github/joshua-y-hub/Deep-learning/blob/main/Cellphone_accessories_1_mill__df.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gensim
!pip install python-Levenshtein
import gensim
import pandas as pd

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.0)
Requirement already satisfied: python-Levenshtein in /usr/local/lib/python3.12/dist-packages (0.27.3)
Requirement already satisfied: Levenshtein==0.27.3 in /usr/local/lib/python3.12/dist-packages (from python-Levenshtein) (0.27.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from Levenshtein==0.27.3->python-Levenshtein) (3.14.5)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
import pandas as pd

# Update the file path to point to your Google Drive
file_path = "/content/drive/MyDrive/Cell_Phones_and_Accessories_5.json"

if os.path.exists(file_path):
    print(f"The file '{file_path}' exists. Proceeding to load it.")
    df = pd.read_json(file_path, lines=True)
    display(df.head())
else:
    print(f"Error: The file '{file_path}' does not exist in your Google Drive. Please ensure the file is in the root of 'My Drive' or adjust the path accordingly.")

The file '/content/drive/MyDrive/Cell_Phones_and_Accessories_5.json' exists. Proceeding to load it.

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"08 4, 2014",A24E3SXTC62LJI,7508492919,{'Color:': ' Bling'},Claudia Valdivia,Looks even better in person. Be careful to not...,Can't stop won't stop looking at it,1407110400,NaN,NaN
1,5,True,"02 12, 2014",A269FLZCB4GIPV,7508492919,NaN,sarah ponce,When you don't want to spend a whole lot of ca...,1,1392163200,NaN,NaN
2,3,True,"02 8, 2014",AB6CHQWHZW4TV,7508492919,NaN,Kai,"so the case came on time, i love the design. I...",Its okay,1391817600,NaN,NaN
3,2,True,"02 4, 2014",A1M117A53LEI8,7508492919,NaN,Sharon Williams,DON'T CARE FOR IT. GAVE IT AS A GIFT AND THEY...,CASE,1391472000,NaN,NaN
4,4,True,"02 3, 2014",A272DUT8M88ZS8,7508492919,NaN,Bella Rodriguez,"I liked it because it was cute, but the studs ...",Cute!,1391385600,NaN,NaN

In [ ]:
df= df.drop(['vote', 'image', 'verified'], axis=1).copy()
df.head()

,overall,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
0,5,"08 4, 2014",A24E3SXTC62LJI,7508492919,{'Color:': ' Bling'},Claudia Valdivia,Looks even better in person. Be careful to not...,Can't stop won't stop looking at it,1407110400
1,5,"02 12, 2014",A269FLZCB4GIPV,7508492919,NaN,sarah ponce,When you don't want to spend a whole lot of ca...,1,1392163200
2,3,"02 8, 2014",AB6CHQWHZW4TV,7508492919,NaN,Kai,"so the case came on time, i love the design. I...",Its okay,1391817600
3,2,"02 4, 2014",A1M117A53LEI8,7508492919,NaN,Sharon Williams,DON'T CARE FOR IT. GAVE IT AS A GIFT AND THEY...,CASE,1391472000
4,4,"02 3, 2014",A272DUT8M88ZS8,7508492919,NaN,Bella Rodriguez,"I liked it because it was cute, but the studs ...",Cute!,1391385600

In [ ]:
df.shape

(1128437, 9)

In [ ]:
# Filter out NaN values before applying text preprocessing
review_text = df.reviewText.dropna().apply(gensim.utils.simple_preprocess)

# Alternative approach: Fill NaN values with empty strings first
# review_text = df.reviewText.fillna('').apply(gensim.utils.simple_preprocess)

In [ ]:
review_text

0          [looks, even, better, in, person, be, careful,...
1          [when, you, don, want, to, spend, whole, lot, ...
2          [so, the, case, came, on, time, love, the, des...
3          [don, care, for, it, gave, it, as, gift, and, ...
4          [liked, it, because, it, was, cute, but, the, ...
                                 ...
1128432    [good, for, viewing, but, doesn, have, button,...
1128433    [was, given, the, rockrok, vr, glasses, headse...
1128434    [super, fun, the, rockroc, vr, headset, is, wa...
1128435    [love, it, ve, had, other, vr, glasses, which,...
1128436                                           [love, it]
Name: reviewText, Length: 1127672, dtype: object

In [ ]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4,
)

In [ ]:
model.build_vocab(review_text, progress_per=1000)

In [ ]:
model.train(review_text, total_examples=model.corpus_count, epochs=model.epochs)

(195368238, 266797320)

In [ ]:
model_save_path = "/content/drive/MyDrive/word2vec-amazon-cell-accessories-reviews-short-GPU.model"
model.save(model_save_path)

print(f"Model saved successfully to: {model_save_path}")

Model saved successfully to: /content/drive/MyDrive/word2vec-amazon-cell-accessories-reviews-short-GPU.model

In [ ]:
model.wv.most_similar("bad")

[('terrible', 0.6864409446716309),
 ('shabby', 0.6419349312782288),
 ('horrible', 0.624489426612854),
 ('disappointing', 0.6038455963134766),
 ('uncommon', 0.572418749332428),
 ('awful', 0.5704721808433533),
 ('keen', 0.568739116191864),
 ('good', 0.5685456991195679),
 ('crappy', 0.560944676399231),
 ('poor', 0.5607509613037109)]

In [ ]:
model.wv.similarity(w1="cheap", w2="inexpensive")

np.float32(0.4373434)